### ISSUE TITLE
How do you deal with inconsistent responses for queue_status

### ISSUE THREAD

**Issue by nerdyness** [emilianodellacasa/ruby-asterisk#15]
Have you used your Gem to query Asterisk's Queues?

I found that Asterisk returns really inconsistent results in response to `queue_status`. E.g. sometimes it returns

```
Response: Success
ActionID: 199
Message: Queue status will follow
```

If I query queue_status again, it may return the whole output including "QueueMembers". I have found Asterisk does this across the board, but in production I use "Asterisk 1.8.11.0".

I've written some ugly code that:
- checks that the response contains /Response: Success/ && /QueueStatusComplete/
- loops over queue_status until the response has been identical 3 times in a row.

How did you solve that problem and are you interested in a PR that attempts to tackle this issue?

**Comment by emilianodellacasa** [comment]
Please feel free to submit a PR if still interested, ugly code that works is ok for me! :-)

**Comment by nerdyness** [comment]
:+1:
I'll send you something when I get around to it but hopefully over the next fortnight.
