### ISSUE TITLE
 NameError on a controller

### ISSUE THREAD

**Issue by brando16** [emilianodellacasa/ruby-asterisk#25]
hi all,
 
i'm newbie to rails and used last releas 5.0.4 install gem is allready ok without problem, but when execute the command to connect to asterdsik this error happens:

NameError (uninitialized constant ConfigsController::RubyAsterisk) 

ConfigsController is the controller where execute this command,

please help me

**Comment by emilianodellacasa** [comment]
I think there is something wrong with your code, could you please show me the part where you are calling the methods?
