### ISSUE TITLE
Adding initialization parameters for Telnet options like Output_log, Waittime, Dump_log, timeout

### ISSUE THREAD

**Issue by emilianodellacasa** [emilianodellacasa/ruby-asterisk#32]
Something has been done in the meantime, let's check what is missing

**Comment by emilianodellacasa** [comment]
@0crat hello

**Comment by 0crat** [comment]
> @0crat hello ([here](https://github.com/emilianodellacasa/ruby-asterisk/issues/32#issuecomment-452732713))

@emilianodellacasa Hey, what's up, how is it going?

**Comment by emilianodellacasa** [comment]
Solved in PR #33

**Comment by 0crat** [comment]
Job `gh:emilianodellacasa/ruby-asterisk#32` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by emilianodellacasa** [comment]
@0crat hello

**Comment by 0crat** [comment]
> @0crat hello ([here](https://github.com/emilianodellacasa/ruby-asterisk/issues/32#issuecomment-479800556))

@emilianodellacasa Hey, what's up, how is it going?
