### ISSUE TITLE
Create new release of ruby-asterisk

### ISSUE THREAD

**Issue by rhughes1** [emilianodellacasa/ruby-asterisk#36]
It seems like the last release is missing lots of features from master. Is it possible to create a new release of this (ie v0.2.0)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
@rhughes1[/z](https://www.0crat.com/u/rhughes1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CE8UGB6NP) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by emilianodellacasa** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/emilianodellacasa/ruby-asterisk/issues/36#issuecomment-513274502))

@emilianodellacasa Thanks for your contribution, @rhughes1[/z](https://www.0crat.com/u/rhughes1)! If you would be a member of [the project](https://www.0crat.com/p/CE8UGB6NP), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/emilianodellacasa/ruby-asterisk/issues/36#issuecomment-513274502))

@emilianodellacasa The job [#36](https://github.com/emilianodellacasa/ruby-asterisk/issues/36) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CE8UGB6NP/11722249-fc8b-4594-bc42-81d1fd6b9873); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by rhughes1** [comment]
@emilianodellacasa Is there an ETA on when this will be complete?

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by emilianodellacasa** [comment]
@rhughes1 I just released the new gem, please check and let me know

**Comment by 0crat** [comment]
The job [#36](https://github.com/emilianodellacasa/ruby-asterisk/issues/36) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)
